/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface De1AdvancedSettingsRequest { 
    heaterPh1Flow?: number | null;
    heaterPh2Flow?: number | null;
    heaterIdleTemp?: number | null;
    heaterPh2Timeout?: number | null;
}

