/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface De1AdvancedSettingsResponse { 
    heaterPh1Flow?: number;
    heaterPh2Flow?: number;
    heaterIdleTemp?: number;
    heaterPh2Timeout?: number;
}

