/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Operation type indicating the nature of the raw message.
 */
export type De1RawOperationType = 'read' | 'write' | 'notify';

export const De1RawOperationType = {
    Read: 'read' as De1RawOperationType,
    Write: 'write' as De1RawOperationType,
    Notify: 'notify' as De1RawOperationType
};

