/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { De1RawMessageType } from './de1RawMessageType';
import { De1RawOperationType } from './de1RawOperationType';


export interface De1RawMessage { 
    type: De1RawMessageType;
    operation: De1RawOperationType;
    /**
     * UUID of the characteristic (len = 4).
     */
    characteristicUUID: string;
    /**
     * The data payload as a hex string.
     */
    payload: string;
}
export namespace De1RawMessage {
}


