/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of raw message indicating whether it\'s a request or response.
 */
export type De1RawMessageType = 'request' | 'response';

export const De1RawMessageType = {
    Request: 'request' as De1RawMessageType,
    Response: 'response' as De1RawMessageType
};

