/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface De1SettingsRequest { 
    usb?: boolean | null;
    fan?: number | null;
    flushTemp?: number | null;
    flushFlow?: number | null;
    flushTimeout?: number | null;
    hotWaterFlow?: number | null;
    steamFlow?: number | null;
    tankTemp?: number | null;
}

