/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MachineSnapshot } from './machineSnapshot';


export interface De1StateGet200Response { 
    snapshot?: MachineSnapshot;
    usbChargerEnabled?: boolean;
}

