/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface De1SettingsResponse { 
    usb?: boolean;
    fan?: number;
    flushTemp?: number;
    flushFlow?: number;
    flushTimeout?: number;
    hotWaterFlow?: number;
    steamFlow?: number;
    tankTemp?: number;
}

