/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DevicesGet200ResponseInner { 
    name?: string;
    id?: string;
    state?: DevicesGet200ResponseInner.StateEnum;
}
export namespace DevicesGet200ResponseInner {
    export type StateEnum = 'connected' | 'disconnected';
    export const StateEnum = {
        Connected: 'connected' as StateEnum,
        Disconnected: 'disconnected' as StateEnum
    };
}


