/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MachineSubstate = 'idle' | 'preparingForShot' | 'preinfusion' | 'pouring' | 'pouringDone' | 'cleaningStart' | 'cleaingGroup' | 'cleanSoaking' | 'cleaningSteam';

export const MachineSubstate = {
    Idle: 'idle' as MachineSubstate,
    PreparingForShot: 'preparingForShot' as MachineSubstate,
    Preinfusion: 'preinfusion' as MachineSubstate,
    Pouring: 'pouring' as MachineSubstate,
    PouringDone: 'pouringDone' as MachineSubstate,
    CleaningStart: 'cleaningStart' as MachineSubstate,
    CleaingGroup: 'cleaingGroup' as MachineSubstate,
    CleanSoaking: 'cleanSoaking' as MachineSubstate,
    CleaningSteam: 'cleaningSteam' as MachineSubstate
};

