/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MachineSubstate } from './machineSubstate';
import { MachineState } from './machineState';


export interface MachineSnapshotState { 
    state?: MachineState;
    substate?: MachineSubstate;
}
export namespace MachineSnapshotState {
}


