/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MachineSnapshot { 
    timestamp?: string;
    state?: object;
    flow?: number;
    pressure?: number;
    targetFlow?: number;
    targetPressure?: number;
    mixTemperature?: number;
    groupTemperature?: number;
    targetMixTemperature?: number;
    targetGroupTemperature?: number;
    profileFrame?: number;
    steamTemperature?: number;
}

