/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MachineState = 'idle' | 'booting' | 'sleeping' | 'heating' | 'preheating' | 'espresso' | 'hotWater' | 'flush' | 'steam' | 'skipStep' | 'cleaning' | 'descaling' | 'transportMode' | 'needsWater' | 'error';

export const MachineState = {
    Idle: 'idle' as MachineState,
    Booting: 'booting' as MachineState,
    Sleeping: 'sleeping' as MachineState,
    Heating: 'heating' as MachineState,
    Preheating: 'preheating' as MachineState,
    Espresso: 'espresso' as MachineState,
    HotWater: 'hotWater' as MachineState,
    Flush: 'flush' as MachineState,
    Steam: 'steam' as MachineState,
    SkipStep: 'skipStep' as MachineState,
    Cleaning: 'cleaning' as MachineState,
    Descaling: 'descaling' as MachineState,
    TransportMode: 'transportMode' as MachineState,
    NeedsWater: 'needsWater' as MachineState,
    Error: 'error' as MachineState
};

