/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Profile { 
    version?: string;
    title?: string;
    notes?: string;
    author?: string;
    beverage_type?: string;
    steps?: Array<object>;
    target_volume?: number;
    target_weight?: number;
    target_volume_count_start?: number;
    tank_temperature?: number;
}

