/**
 * Rea Prime API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShotSettings { 
    steamSetting?: number;
    targetSteamTemp?: number;
    targetSteamDuration?: number;
    targetHotWaterTemp?: number;
    targetHotWaterVolume?: number;
    targetHotWaterDuration?: number;
    targetShotVolume?: number;
    groupTemp?: number;
}

